{{
exports.publishOn = new Date().toString();
}}


POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTA0MjI4NjAsImV4cCI6MTc1MDQyNjQ2MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.5VB9CSRAk5fXVhJ-gy0wz8TLXjhnX1GKVLd-caO9q90
{
  "title": "What's new with NestJS",
  "postType": "post",
  "slug": "new-with-nestjs001",
  "status": "draft",
  "content": "test content",
  "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n }",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "{{publishOn}}",
  "tags":[1],
  "metaOptions" : {
    "metaValue": "{ \"sidebarEnabled\": true, \"footerActive\": true }"
  }
}


POST http://localhost:3000/posts/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTA0OTE2NjQsImV4cCI6MTc1MDQ5NTI2NCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.jNTqCvlfojVdRnAv06Rgj5AXideDPos8vOvFeYSOo88


{
"posts":[
  {
    "title": "Advanced NestJS Authentication",
    "postType": "post",
    "slug": "advanced-nestjs-auth-214",
    "status": "published",
    "content": "Deep dive into NestJS authentication strategies",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Article\"\r\n }",
    "featuredImageUrl": "http://localhost.com/images/auth-guide.jpg",
    "publishOn": "2024-03-17T09:30:00+0000",
    "tags":[1],
    "metaOptions" : {
      "metaValue": "{ \"sidebarEnabled\": false, \"footerActive\": true }"
      }
  },
  {
    "title": "Building GraphQL APIs with NestJS",
    "postType": "post",
    "slug": "nestjs-graphql-apis-215",
    "status": "published",
    "content": "Complete guide to GraphQL integration in NestJS",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"TechArticle\"\r\n }",
    "featuredImageUrl": "http://localhost.com/images/graphql-tutorial.jpg",
    "publishOn": "2024-03-18T14:15:00+0000",
    "tags":[1],
    "metaOptions" : {
      "metaValue": "{ \"sidebarEnabled\": true, \"footerActive\": false }"
      }
  }
]}