POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc1MDQyOTA4NywiZXhwIjoxNzUwNTE1NDg3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.KoxYucIdWjZ_fuSUbbG3xd1zblfPvuyRFkyciNR2RVI"
}